#' ChatGPT: Parallelize Code
#'
#' @param code The R code to be parallelized by ChatGPT. If not provided, it will
#'   use what's copied on the clipboard.
#'
#' @examples
#' \dontrun{
#' cat(parallelize_code("for (i in 1:10) { print(i) }"))
#' }
#'
#' @importFrom clipr read_clip
#'
#' @return A character value with the response generated by ChatGPT.
#'
#' @export
#'
parallelize_code <- function(code = clipr::read_clip(allow_non_interactive = TRUE)) {
  # Nettoyage du code
  code <- paste(gsub('"', "'", code), collapse = "\n")
  
  # Build the prompt
  prompt <- paste0(
    "Rewrite the following R code using parallel computing best practices. ",
    "Preferably use packages like 'furrr','parallel', 'future', or 'foreach'. ",
    "Ensure the output is equivalent. Code to parallelize:\n\n",
    code
  )
  
  # Call GPT via existing function
  parse_response(gpt_get_completions(prompt))
}
